version: 2.1


jobs:  
  deployment-and-api-tests:    
    build: # name of your job
    machine: # executor type
      image: ubuntu-2004:202010-01
    steps:   
      - checkout  
      - run:
          name: 'Test Scheduler Build Block API'
          command:
            'echo testing all examples in /examples against test suite in /test'     
      - run:
          name: Deploy Mock APP for Scheduler BB API and PyTest Containers
          command: cd examples/mock && docker-compose up --build -d
      - run:
          name: Check Status of Mock App and API Testing Containers
          command: docker ps
      - run:
          name: Testing Scheduler BB API 
          command: 'echo testing using conatainers' 
      - run:
          name: Check Status of Testing Containers are Deployed 
          command: docker ps
      - run:
          name: Create Test Result Directory
          command: mkdir -p /home/circleci/test_result
      - run:
          name: Run cucumber tests against Register BB Mock 
          command: docker  exec -i pytest  pytest  -s --json-report --json-report-indent=4 --json-report-file=/home/circleci/test_result/smoke_testing_report.json
                
      - store_test_results:  
          path: ../test_result

    
workflows:  
  deployment-and-api-tests:    
    jobs:      
      - deployment-and-api-tests:
          filters:            
            branches:
              only:
                - main