version: 2.1


jobs:  
  deployment-and-api-tests:    
    build: # name of your job
    machine: # executor type
      image: ubuntu-2004:202010-01
    steps:   
      - checkout  
      - run:
          name: 'Test Scheduler Build Block API'
          command:
            'echo testing all examples in /examples against test suite in /test'     
      - run:
          name: Deploy Mock APP for Scheduler BB API and PyTest Containers
          command: cd examples/mock && docker-compose up --build -d
      - run:
          name: Check Status of Mock App and API Testing Containers
          command: docker ps
      - run:
          name: Testing Scheduler BB API 
          command: 'echo testing using conatainers' 
      - run:
          name: Check Status of Testing Containers are Deployed 
          command: docker ps
      - run:
          name: Testing Scheduler BB API 
          command: 'echo testing using conatainers' 
      
      - run:
          name: Run cucumber tests against Register BB Mock 
          command: docker  exec -i pytest  curl -X GET http://myapi:3000/event/list_details
          
      - run:
          name: Create test-results directory
          command: mkdir /home/circleci/project/test-results
      - run:
          name: Run cucumber tests against Register BB Mock 
          command: docker  exec -i pytest  pytest -k smoke  -s --json-report --json-report-indent=4 --json-report-file=/home/circleci/project/test-results/smoke_testing_report.json
                
      - store_test_results:
          path: /home/circleci/project/test-results
          destination: /home/circleci/project/test-results
      -  store_artifacts:
          path: /home/circleci/project/test-results 
    
workflows:  
  deployment-and-api-tests:    
    jobs:      
      - deployment-and-api-tests:
          filters:            
            branches:
              only:
                - main
