version: "3"
services:
  mockoon:
    image: mockoon/cli:latest
    command: -d /data # this is where the change takes place
    container_name: myapi
    ports:
      - "3000:3000"
    networks:
      demo:
    volumes:
      - type: bind
        source: ../../api/Scheduler_OpenAPI_17042023_V3.json    
        target: /data 
  pytest:
   build:
     context: ../../test/.
   container_name: pytest
   volumes:
      - type: bind
        source: ../../test
        target: ../../test
      - type: bind
        source: ../../test/test-results
        target: ../../test/test-results
   tty: true
   stdin_open: true
   networks:
      demo:


networks:
      demo:
 
